### ISSUE TITLE
How to train NER and Relational model on custom dataset?

### ISSUE THREAD

**Issue by karndeepsingh** [AdirthaBorgohain/NER-RE#1]
Hi Thanks for sharing this amazing work, I have following doubts please help me to understand:

1. I have trained Ner and Relation model using BERT from spacy, but I can see you are using knowledge graph in between NER and Relation Extraction model. I just want to understand how it is different from what I have been using and what you have implemented? Here is the link from spacy which I have used  to NER and realtion model https://github.com/explosion/projects/tree/v3/tutorials/rel_component
2. If I want to use your work, how can I annotate or prepare my text for annotation so that I can build Knowldege Graph as well and do NER and Relation extraction at the same time.

Please help me to understand the process. I am stuck in  my project.

Thanks

**Comment by AdirthaBorgohain** [comment]
Hi. Glad you found the project interesting.  First of all, I would like to tell you that I have a few changes to make to the code which I will do so shortly. So, things could get a bit easier by then. As for your questions:

1. The difference in the tutorial you have linked to is that the spacy tutorial does not use any entity linker in between. They directly proceed from extracting entities with NER to extracting relations between the entities. The NER and RE components in this repo is somewhat the same thing although I have made some modifications here and there. Entity linking with Custom Knowledge Base is absent there.

2. If you want to use the code from this project on your own data, you'd have to parse your data in the jsonl format that is provided inside the assets folder of NER, RE and EL directories.  Once you have your data in the given jsonl format, you can simply then convert those jsonl files to spacy format and proceed to train the models. (this flow is configured in the ``project.yml`` files of both NER and RE directories. There is no training for the entity linker but you do need to generate the index files from the jsonl knowledge base file) Check out the small README.md files provided in all the directories. Both NER and RE models would be trained separately.  As for entity linking, you just need to generate the index files (files are kept inside indexes folder) and its ready to use. Hope this helps.

**Comment by karndeepsingh** [comment]
> Hi. Glad you found the project interesting. First of all, I would like to tell you that I have a few changes to make to the code which I will do so shortly. So, things could get a bit easier by then. As for your questions:
> 
> 1. The difference in the tutorial you have linked to is that the spacy tutorial does not use any entity linker in between. They directly proceed from extracting entities with NER to extracting relations between the entities. The NER and RE components in this repo is somewhat the same thing although I have made some modifications here and there. Entity linking with Custom Knowledge Base is absent there.
> 2. If you want to use the code from this project on your own data, you'd have to parse your data in the jsonl format that is provided inside the assets folder of NER, RE and EL directories.  Once you have your data in the given jsonl format, you can simply then convert those jsonl files to spacy format and proceed to train the models. (this flow is configured in the `project.yml` files of both NER and RE directories. There is no training for the entity linker but you do need to generate the index files from the jsonl knowledge base file) Check out the small README.md files provided in all the directories. Both NER and RE models would be trained separately.  As for entity linking, you just need to generate the index files (files are kept inside indexes folder) and its ready to use. Hope this helps.

Thank you again for this great answer. I was just wondering, how could I generate JSONL formate for my dataset which has long pargraphs and in which I have to mark entities as well relationships. Do we need to manually annotate Entites in paragraph as well as relationships and then generate JSONL? I am just trying to understand, how you would have approached when you have recieved the raw text and how you would have generated JSONL format out of it.

Please help. Thanks Again.

**Comment by karndeepsingh** [comment]
Hi,
I also a one more doubt, what made you to train the Relational model using Knowledge graph? why didn't you use the direct method provided by spacy? Is there any improvement when we use the knowledge graph?

Please, can you also refer any proper documentation or paper where these things explained in detail so that i can read and prepare the dataset for knowledge graph and train NER AND RELATION model.

Thank you so much

**Comment by AdirthaBorgohain** [comment]
> > Hi. Glad you found the project interesting. First of all, I would like to tell you that I have a few changes to make to the code which I will do so shortly. So, things could get a bit easier by then. As for your questions:
> > 
> > 1. The difference in the tutorial you have linked to is that the spacy tutorial does not use any entity linker in between. They directly proceed from extracting entities with NER to extracting relations between the entities. The NER and RE components in this repo is somewhat the same thing although I have made some modifications here and there. Entity linking with Custom Knowledge Base is absent there.
> > 2. If you want to use the code from this project on your own data, you'd have to parse your data in the jsonl format that is provided inside the assets folder of NER, RE and EL directories.  Once you have your data in the given jsonl format, you can simply then convert those jsonl files to spacy format and proceed to train the models. (this flow is configured in the `project.yml` files of both NER and RE directories. There is no training for the entity linker but you do need to generate the index files from the jsonl knowledge base file) Check out the small README.md files provided in all the directories. Both NER and RE models would be trained separately.  As for entity linking, you just need to generate the index files (files are kept inside indexes folder) and its ready to use. Hope this helps.
> 
> Thank you again for this great answer. I was just wondering, how could I generate JSONL formate for my dataset which has long pargraphs and in which I have to mark entities as well relationships. Do we need to manually annotate Entites in paragraph as well as relationships and then generate JSONL? I am just trying to understand, how you would have approached when you have recieved the raw text and how you would have generated JSONL format out of it.
> 
> Please help. Thanks Again.

To generate these type of JSONL files, you could either do it manually (harder way) or you could use prodigy (https://prodi.gy/). Its from the same creators of spacy and generates annotations in the format given.  

To answer your question of if you have raw texts, you could then proceed to annotate the texts for ner and relation extraction together by using ``rel.manual`` recipe in prodigy. Once you have annotated the data for both ner and relation extraction and have generated the JSONL files from prodigy, you could simply remove the 'relations' field from the JSONL file to be able to train the NER model on it. For training the relation extraction model, you can use the JSONL file as it is.

**Comment by AdirthaBorgohain** [comment]
> Hi, I also a one more doubt, what made you to train the Relational model using Knowledge graph? why didn't you use the direct method provided by spacy? Is there any improvement when we use the knowledge graph?
> 
> Please, can you also refer any proper documentation or paper where these things explained in detail so that i can read and prepare the dataset for knowledge graph and train NER AND RELATION model.
> 
> Thank you so much

The relational model is not trained using any knowledge graph. I have used a knowledge base to perform entity linking which is independent of relation extraction. The idea behind entity linking is basically normalizing all extracted entities to its base or most commonly known form. For eg. "DNA" is the most common form of the word we know. But this word can occur as "Deoxyribonucleic acid" in some text. Essentially however both of these mean the same thing. Hence we can link the word "Deoxyribonucleic acid" to "DNA" automatically with the use of entity linker. 

Hope this clears things a bit.

**Comment by karndeepsingh** [comment]
> > > Hi. Glad you found the project interesting. First of all, I would like to tell you that I have a few changes to make to the code which I will do so shortly. So, things could get a bit easier by then. As for your questions:
> > > 
> > > 1. The difference in the tutorial you have linked to is that the spacy tutorial does not use any entity linker in between. They directly proceed from extracting entities with NER to extracting relations between the entities. The NER and RE components in this repo is somewhat the same thing although I have made some modifications here and there. Entity linking with Custom Knowledge Base is absent there.
> > > 2. If you want to use the code from this project on your own data, you'd have to parse your data in the jsonl format that is provided inside the assets folder of NER, RE and EL directories.  Once you have your data in the given jsonl format, you can simply then convert those jsonl files to spacy format and proceed to train the models. (this flow is configured in the `project.yml` files of both NER and RE directories. There is no training for the entity linker but you do need to generate the index files from the jsonl knowledge base file) Check out the small README.md files provided in all the directories. Both NER and RE models would be trained separately.  As for entity linking, you just need to generate the index files (files are kept inside indexes folder) and its ready to use. Hope this helps.
> > 
> > 
> > Thank you again for this great answer. I was just wondering, how could I generate JSONL formate for my dataset which has long pargraphs and in which I have to mark entities as well relationships. Do we need to manually annotate Entites in paragraph as well as relationships and then generate JSONL? I am just trying to understand, how you would have approached when you have recieved the raw text and how you would have generated JSONL format out of it.
> > Please help. Thanks Again.
> 
> To generate these type of JSONL files, you could either do it manually (harder way) or you could use prodigy (https://prodi.gy/). Its from the same creators of spacy and generates annotations in the format given.
> 
> To answer your question of if you have raw texts, you could then proceed to annotate the texts for ner and relation extraction together by using `rel.manual` recipe in prodigy. Once you have annotated the data for both ner and relation extraction and have generated the JSONL files from prodigy, you could simply remove the 'relations' field from the JSONL file to be able to train the NER model on it. For training the relation extraction model, you can use the JSONL file as it is.

So, once we got data annotated using Prodigy and convert it into JSONL(consist relation data as well) then how we gonna convert it into spacy.bin format? Any specific command is being used to convert it from JSONL to spacy.bin or we have to code JSONL to spacy.bin?

**Comment by AdirthaBorgohain** [comment]
You can find the command in the project.yml file of each NER and RE directories. For ease of use you can simply run ``spacy run all_gpu`` in NER and RE directories accordingly if you want to train using transformers.  Internally, ``parse_data.py`` script is used which is under scripts folder in NER and RE directories.  ``parse_data.py`` converts from JSONL to spacy format. If you use ``spacy run all_gpu``, it will proceed to first parsing the data and training the model.

**Comment by AdirthaBorgohain** [comment]
> > > > Hi. Glad you found the project interesting. First of all, I would like to tell you that I have a few changes to make to the code which I will do so shortly. So, things could get a bit easier by then. As for your questions:
> > > > 
> > > > 1. The difference in the tutorial you have linked to is that the spacy tutorial does not use any entity linker in between. They directly proceed from extracting entities with NER to extracting relations between the entities. The NER and RE components in this repo is somewhat the same thing although I have made some modifications here and there. Entity linking with Custom Knowledge Base is absent there.
> > > > 2. If you want to use the code from this project on your own data, you'd have to parse your data in the jsonl format that is provided inside the assets folder of NER, RE and EL directories.  Once you have your data in the given jsonl format, you can simply then convert those jsonl files to spacy format and proceed to train the models. (this flow is configured in the `project.yml` files of both NER and RE directories. There is no training for the entity linker but you do need to generate the index files from the jsonl knowledge base file) Check out the small README.md files provided in all the directories. Both NER and RE models would be trained separately.  As for entity linking, you just need to generate the index files (files are kept inside indexes folder) and its ready to use. Hope this helps.
> > > 
> > > 
> > > Thank you again for this great answer. I was just wondering, how could I generate JSONL formate for my dataset which has long pargraphs and in which I have to mark entities as well relationships. Do we need to manually annotate Entites in paragraph as well as relationships and then generate JSONL? I am just trying to understand, how you would have approached when you have recieved the raw text and how you would have generated JSONL format out of it.
> > > Please help. Thanks Again.
> > 
> > 
> > To generate these type of JSONL files, you could either do it manually (harder way) or you could use prodigy (https://prodi.gy/). Its from the same creators of spacy and generates annotations in the format given.
> > To answer your question of if you have raw texts, you could then proceed to annotate the texts for ner and relation extraction together by using `rel.manual` recipe in prodigy. Once you have annotated the data for both ner and relation extraction and have generated the JSONL files from prodigy, you could simply remove the 'relations' field from the JSONL file to be able to train the NER model on it. For training the relation extraction model, you can use the JSONL file as it is.
> 
> So, once we got data annotated using Prodigy and convert it into JSONL(consist relation data as well) then how we gonna convert it into spacy.bin format? Any specific command is being used to convert it from JSONL to spacy.bin or we have to code JSONL to spacy.bin?

You can find the command in the project.yml file of each NER and RE directories. For ease of use you can simply run ``spacy run all_gpu`` in NER and RE directories accordingly if you want to train using transformers.  Internally, ``parse_data.py`` script is used which is under scripts folder in NER and RE directories.  ``parse_data.py`` converts from JSONL to spacy format. If you use ``spacy run all_gpu``, it will proceed to first parsing the data and training the model.

**Comment by karndeepsingh** [comment]
> > > > > Hi. Glad you found the project interesting. First of all, I would like to tell you that I have a few changes to make to the code which I will do so shortly. So, things could get a bit easier by then. As for your questions:
> > > > > 
> > > > > 1. The difference in the tutorial you have linked to is that the spacy tutorial does not use any entity linker in between. They directly proceed from extracting entities with NER to extracting relations between the entities. The NER and RE components in this repo is somewhat the same thing although I have made some modifications here and there. Entity linking with Custom Knowledge Base is absent there.
> > > > > 2. If you want to use the code from this project on your own data, you'd have to parse your data in the jsonl format that is provided inside the assets folder of NER, RE and EL directories.  Once you have your data in the given jsonl format, you can simply then convert those jsonl files to spacy format and proceed to train the models. (this flow is configured in the `project.yml` files of both NER and RE directories. There is no training for the entity linker but you do need to generate the index files from the jsonl knowledge base file) Check out the small README.md files provided in all the directories. Both NER and RE models would be trained separately.  As for entity linking, you just need to generate the index files (files are kept inside indexes folder) and its ready to use. Hope this helps.
> > > > 
> > > > 
> > > > Thank you again for this great answer. I was just wondering, how could I generate JSONL formate for my dataset which has long pargraphs and in which I have to mark entities as well relationships. Do we need to manually annotate Entites in paragraph as well as relationships and then generate JSONL? I am just trying to understand, how you would have approached when you have recieved the raw text and how you would have generated JSONL format out of it.
> > > > Please help. Thanks Again.
> > > 
> > > 
> > > To generate these type of JSONL files, you could either do it manually (harder way) or you could use prodigy (https://prodi.gy/). Its from the same creators of spacy and generates annotations in the format given.
> > > To answer your question of if you have raw texts, you could then proceed to annotate the texts for ner and relation extraction together by using `rel.manual` recipe in prodigy. Once you have annotated the data for both ner and relation extraction and have generated the JSONL files from prodigy, you could simply remove the 'relations' field from the JSONL file to be able to train the NER model on it. For training the relation extraction model, you can use the JSONL file as it is.
> > 
> > 
> > So, once we got data annotated using Prodigy and convert it into JSONL(consist relation data as well) then how we gonna convert it into spacy.bin format? Any specific command is being used to convert it from JSONL to spacy.bin or we have to code JSONL to spacy.bin?
> 
> You can find the command in the project.yml file of each NER and RE directories. For ease of use you can simply run `spacy run all_gpu` in NER and RE directories accordingly if you want to train using transformers. Internally, `parse_data.py` script is used which is under scripts folder in NER and RE directories. `parse_data.py` converts from JSONL to spacy format. If you use `spacy run all_gpu`, it will proceed to first parsing the data and training the model.

Thanks again @AdirthaBorgohain . Waiting for your update on your Work.

**Comment by karndeepsingh** [comment]
> > > > > > Hi. Glad you found the project interesting. First of all, I would like to tell you that I have a few changes to make to the code which I will do so shortly. So, things could get a bit easier by then. As for your questions:
> > > > > > 
> > > > > > 1. The difference in the tutorial you have linked to is that the spacy tutorial does not use any entity linker in between. They directly proceed from extracting entities with NER to extracting relations between the entities. The NER and RE components in this repo is somewhat the same thing although I have made some modifications here and there. Entity linking with Custom Knowledge Base is absent there.
> > > > > > 2. If you want to use the code from this project on your own data, you'd have to parse your data in the jsonl format that is provided inside the assets folder of NER, RE and EL directories.  Once you have your data in the given jsonl format, you can simply then convert those jsonl files to spacy format and proceed to train the models. (this flow is configured in the `project.yml` files of both NER and RE directories. There is no training for the entity linker but you do need to generate the index files from the jsonl knowledge base file) Check out the small README.md files provided in all the directories. Both NER and RE models would be trained separately.  As for entity linking, you just need to generate the index files (files are kept inside indexes folder) and its ready to use. Hope this helps.
> > > > > 
> > > > > 
> > > > > Thank you again for this great answer. I was just wondering, how could I generate JSONL formate for my dataset which has long pargraphs and in which I have to mark entities as well relationships. Do we need to manually annotate Entites in paragraph as well as relationships and then generate JSONL? I am just trying to understand, how you would have approached when you have recieved the raw text and how you would have generated JSONL format out of it.
> > > > > Please help. Thanks Again.
> > > > 
> > > > 
> > > > To generate these type of JSONL files, you could either do it manually (harder way) or you could use prodigy (https://prodi.gy/). Its from the same creators of spacy and generates annotations in the format given.
> > > > To answer your question of if you have raw texts, you could then proceed to annotate the texts for ner and relation extraction together by using `rel.manual` recipe in prodigy. Once you have annotated the data for both ner and relation extraction and have generated the JSONL files from prodigy, you could simply remove the 'relations' field from the JSONL file to be able to train the NER model on it. For training the relation extraction model, you can use the JSONL file as it is.
> > > 
> > > 
> > > So, once we got data annotated using Prodigy and convert it into JSONL(consist relation data as well) then how we gonna convert it into spacy.bin format? Any specific command is being used to convert it from JSONL to spacy.bin or we have to code JSONL to spacy.bin?
> > 
> > 
> > You can find the command in the project.yml file of each NER and RE directories. For ease of use you can simply run `spacy run all_gpu` in NER and RE directories accordingly if you want to train using transformers. Internally, `parse_data.py` script is used which is under scripts folder in NER and RE directories. `parse_data.py` converts from JSONL to spacy format. If you use `spacy run all_gpu`, it will proceed to first parsing the data and training the model.
> 
> Thanks again @AdirthaBorgohain . Waiting for update on your Work.
