### ISSUE TITLE
Relation Extraction - Binds and Regulates meaning

### ISSUE THREAD

**Issue by SraavanChevireddy** [AdirthaBorgohain/NER-RE#2]
Hello Adirtha - Thank you for the simplified version of the relation extraction model. This is working perfectly on the dataset you have. But, the MAP_LABELS is hard-coded for Regulates for relations in `parse_data.py`.

I'm using curious about this because IT WORKED FOR ME when I hardcoded it as **Regulates**. Is this a predefined spacy keyword in Spacy, or something that is going with the project configuration file? Your Annotated dataset doesn't have anything with that word.

Plus - Why you didn't use SYMM_LABELS as other guys do for relation extraction as per Spacy Tutorial.

**Comment by AdirthaBorgohain** [comment]
Hello Sraavan. Glad you could get the codebase working. In ``parse_data.py`` file, for the MAP_LABELS variable, it can vary depending on the dataset. In my case, what I am doing is in the annotated data, there are relation labels like Pos-Reg, Neg-Reg,  Reg, No-rel. These labels are getting converted to a single label ``Regulates`` in my case. So, in the end the relation extraction model will predict only two labels - Regulates and Binds (as written in parse_data.py). If you have a different dataset and want to keep the labels as it is in the annotated data labes, for the MAP_LABELS dictionary, you can keep both the key and values same. The Keys and Values would consist of all the relation labels you have in your annotated dataset. Hope it makes sense to you. Let me know if you difficulty understanding it!

**Comment by AdirthaBorgohain** [comment]
As for SYMM_LABELS, that can be used as well.  But it is just a variable name, in my case I changed it to MAP_LABLES as it made for sense for me to understand as to what the variable does in the ``parse_data.py`` script.

**Comment by SraavanChevireddy** [comment]
Oh Yeah! this absolutely makes sense. Thanks for the quick response.
