### ISSUE TITLE
Reg: Annotation tool

### ISSUE THREAD

**Issue by ajsirsik** [AdirthaBorgohain/NER-RE#4]
Hello Adirtha, 
Many thanks for implementation, May I know, How data was annotated for this implementation 
Thanks again 

Best regards

**Comment by AdirthaBorgohain** [comment]
Hello. Glad you found this helpful. For data annotation, you can use any tool you want. You just need to make sure once that data is annotated, the data is that formatted as in the jsonl files. explosion.ai's [prodigy](https://prodi.gy/) tool can be used to get this format directly out of the box. Just note that [prodigy](https://prodi.gy/) is a paid tool however. Thanks!
