### ISSUE TITLE
Error on rel_pipe.py

### ISSUE THREAD

**Issue by FelipeSBarros** [AdirthaBorgohain/NER-RE#5]
Hi @AdirthaBorgohain . 
Just to let you know that project might need an update. 
I was using it as a reference and found a problem that was already upodated by [explosion team](https://github.com/explosion/spaCy/discussions/11205#discussioncomment-3278945).
The specific problem I found is related with  [rel_pipe.py](https://github.com/AdirthaBorgohain/NER-RE/blob/main/RE/scripts/rel_pipe.py#L211). 
Best regards

**Comment by AdirthaBorgohain** [comment]
Hey, @FelipeSBarros. Yes indeed it looks like the file `rel_pipe.py` needs to be updated.. Updating it. Thanks a lot for the heads up.
